---
ID: "8c5d2ff2-c585-4353-b8a6-bfef53c6ac9a"
Parent: "a42585a0-9420-4ee6-a770-c7d66a6cd69a"
Template: "a42585a0-9420-4ee6-a770-c7d66a6cd69a"
Path: /sitecore/templates/Feature/Search/PhraseSearch/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200709T021456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "ce409505-08ec-461e-8ef4-4514ca4cede2"
      Hint: PlaceholderText
      Value: $name
