---
ID: "a24d4579-fb4f-43f8-ba1b-f915cc6e4d35"
Parent: "933251eb-e57c-4257-9a84-8782985cd1fa"
Template: "933251eb-e57c-4257-9a84-8782985cd1fa"
Path: /sitecore/templates/Feature/Carousel/Carousels Folder/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200717T060332Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
