---
ID: "bae0a9e9-3985-4825-908e-0c9758a3648b"
Parent: "baeadf11-4fe3-4cd1-8d52-98697bba3343"
Template: "baeadf11-4fe3-4cd1-8d52-98697bba3343"
Path: /sitecore/templates/Feature/DynamicLayout/_NumberOfColumns/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191202T044503Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
