---
ID: "47b076b5-589e-419e-bbe6-8209f0f364fa"
Parent: "9bebcce3-0935-464c-8150-2b19e23c7fae"
Template: "9bebcce3-0935-464c-8150-2b19e23c7fae"
Path: "/sitecore/templates/Feature/GeneralContent/Page Section/Page Section Decor-Sides Folder/__Standard Values"
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {9BEBCCE3-0935-464C-8150-2B19E23C7FAE}
    {609031F5-0732-45E4-B146-EE1A08A5DEA9}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200707T232435Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
